#!/bin/bash

PWD="$(pwd)"
BASE_DIR="$PWD"
BCM_DIR="$PWD/bcm2835-1.46"
ARDUPI_DIR="$PWD/ardupi2.0"

echo ""
echo "Checking system..."

if [ -d "$BCM_DIR" ]; then
	rm -rf "$BCM_DIR"
fi

if [ -d "$ARDUPI_DIR" ]; then
        rm -rf "$ARDUPI_DIR"
fi

sleep 1

echo "Checking required packages..."

sudo apt-get update

dpkg -s g++ 2>/dev/null >/dev/null || sudo apt-get -y install g++
dpkg -s zip 2>/dev/null >/dev/null || sudo apt-get -y install zip
dpkg -s unzip 2>/dev/null >/dev/null || sudo apt-get -y install unzip

echo "Pacakes installed..."
echo "Unzipping libraries, this will take a while..."

unzip "$PWD/bcm2835_146.zip" && cd "$BCM_DIR" && ./configure && sudo make && sudo make install

sleep 1

cd "$BASE_DIR" && tar -xzvf ardupi_for_raspberry_pi_2.tar.gz && cd "$ARDUPI_DIR" && g++ -c arduPi.cpp -o arduPi.o

echo ""
echo "Libraries compiled successfully!!! You can now use arduPi in your projects"
echo "Ardupi library is compiled in ardupi directory"
echo ""

exit 0

